#!/bin/bash
# Github : https://github.com/m404ehf
clear
merah='\e[31m'
ijo='\e[1;32m'
kuning='\e[1;33m'
biru='\e[1;34m'
NC='\e[0m'
#intro
printf "${ijo}
   ╔═════════════════════════════════════════════╗

    ████████████████  ██╗  ██  ╔██████╗  ██╗  ██
        ██║  ██  ║██  ██║  ██  ██    ██  ██║  ██
        ██║  ██  ║██  ███████  ██    ██  ███████
        ██╝  ██  ╚██       ██  ╚██████╝       ██ 		   ${merah}

   ╚════════════════════════════════════════════╝
	      SMS Gratis(semoga berhasil)
	      oleh : M 404
	          (SELAMAT MENCOBA)
"
printf "${kuning}__________________________________________________${NC}\n\n"
sms(){
	main(){
	printf "${kuning}[+]${NC} NOMOR TUJUAN : ";read Num
	printf "${kuning}[+]${NC} Message : ";read Message
	send=$(curl 'http://nandrbiz1.com/smsgratis.php' -d "num=$Num&message=$Message" -s)
	if [[ $send == "SMS Telah Dikirim" ]]
	then
		printf "${ijo}[SENT]${NC} [Message : $Message] [To : $Num]\n"
	else
		printf "${merah}[FAIL]${NC} [Reason : $send]\n"
	fi
}
main
for (( ; ;))
do
printf "${kuning}[+]${NC} Again (y/n) : ";read again
if [[ $again == 'y' ]]
then
	main
elif [[ $again == 'n' ]]; then
	echo "Bye.."
	exit
else
	echo "SALAH BOSS"
	exit
fi
done
}
sms
